import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticPaths, GetStaticProps } from "next";
import { ParsedUrlQuery } from "querystring";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  message: string;
}

export default function Home({ message }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>{message}</h1>
        </div>
      </main>
    </>
  );
}

export interface StaticProps {
  props: {
    [key in string]: Object | string | undefined;
  };
  revalidate: number;
}

export type StaticPath = {
  slug: string[]; //possible slug path, location like /sydney, station like /smoothfmsydney or aka like /smoothsydney
};

export interface StaticPaths {
  paths: { params: StaticPath }[];
  fallback: boolean | "blocking";
}
export const mapUrlQueryToSlug0 = (params?: ParsedUrlQuery): string | undefined => {
  console.log("params", params);
  if (!params) return undefined;
  const { slug } = params as StaticPath;
  return slug && slug[0] ? slug[0].toLowerCase() : undefined;
};
export const getStaticProps: GetStaticProps = async ({ params }) => {
  const slug0 = mapUrlQueryToSlug0(params) ?? "root";
  return {
    revalidate: 30,
    props: {
      message: slug0 + " " + new Date().toISOString(),
    },
  };
};
export const getStaticPaths: GetStaticPaths = () => {
  //async if needed
  return {
    fallback: "blocking",
    paths: [
      { params: { slug: ["sydney"] } },
      { params: { slug: ["melbourne"] } },
      { params: { slug: ["brisbane"] } },
      { params: { slug: ["perth"] } },
      { params: { slug: ["adelaide"] } },
      { params: { slug: ["goldcoast"] } },
      { params: { slug: ["canberra"] } },
      { params: { slug: ["hobart"] } },
      { params: { slug: ["darwin"] } },
      { params: { slug: ["newcastle"] } },
      { params: { slug: ["centralcoast"] } },
      { params: { slug: ["geelong"] } },
      { params: { slug: ["sunshinecoast"] } },
      { params: { slug: ["wollongong"] } },
      { params: { slug: ["toowoomba"] } },
      { params: { slug: ["bendigo"] } },
      { params: { slug: ["ballarat"] } },
      { params: { slug: ["alburywodonga"] } },
      { params: { slug: ["townsville"] } },
      { params: { slug: ["mackay"] } },
      { params: { slug: ["rockhampton"] } },
      { params: { slug: ["cairns"] } },
    ],
  };
};
